services:
  heimdall:
    build: "."
    networks:
      metaploy-network:
        aliases:
          - heimdall
    volumes:
      - nginx-config-volume:/etc/nginx/sites-enabled

networks:
  metaploy-network:
    external: true
    name: metaploy-network

volumes:
  nginx-config-volume:
    external: true
    name: metaploy-nginx-config-volume